config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/auth/google_oauth2/callback', to: 'sessions/sessions#omniauth'

  get '/login', to: 'sessions/sessions#login', as: 'login'
  post '/login', to: 'sessions/sessions#create'
  get '/logout', to: 'sessions/sessions#logout', as: 'logout'

  resources :victims, controller: 'victims/users' do
    resources :incidents, controller: 'victims/incidents'
  end

  resources :volunteers, controller: 'volunteers/users' do
    resources :victims, controller: 'volunteers/victims'
    resources :incidents, controller: 'volunteers/incidents'
  end

  resources :incidents, controller: 'incidents/incidents', only: [:index, :show, :update] do
    collection do
      get :not_yet_contacted
      get :not_yet_assigned
      get :time_occurred_desc
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/incident.rb
class Incident < ApplicationRecord
  belongs_to :victim
  has_many :volunteers

  validates :description, :location, :request_translator, :request_translator, presence: true

  scope :not_yet_contacted, -> { where("contact_status = ?", "Not Yet Contacted") }
  scope :not_yet_assigned, -> { where(:volunteer_id => nil) }
  scope :time_occurred_desc, -> { order(time_occurred: :desc)}

  def self.search_by(search_term)
    where("LOWER(location) LIKE :search_term OR LOWER(language) LIKE :search_term",
      search_term: "%#{search_term.downcase}%")
  end

end

app/models/victim.rb
class Victim < ApplicationRecord
    has_secure_password

    has_many :incidents
    has_many :volunteers, through: :incidents
    accepts_nested_attributes_for :incidents

    validates :name, :email, presence: true
    validates :password, presence: true, on: :create
    validates :email, uniqueness: { case_sensitive: false}
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
    validates :password, confirmation: true, on: :create

end

app/controllers/incidents/incidents_controller.rb
class Incidents::IncidentsController < ApplicationController
    include IncidentsHelper

    before_action :require_volunteer_login
    before_action :set_incident, only: [:show, :update]
    before_action :set_victim, only: [:show, :update]

    def index
        @incidents = Incident.all
        if params[:search]
            @search_term = params[:search]
            @incidents = @incidents.search_by(@search_term)
        end
    end

    
    def not_yet_contacted
        @incidents = Incident.not_yet_contacted
        render action: :index
    end

    def not_yet_assigned
        @incidents = Incident.not_yet_assigned
        render action: :index
    end

    def time_occurred_desc
        @incidents = Incident.time_occurred_desc
        render action: :index
    end

    def update
        @incident.update(incident_params)
        redirect_to incident_path(@incident)
    end

    private

    def incident_params
        params.require(:incident).permit(:volunteer_id, :notes)
    end

    def set_incident
        @incident = Incident.find_by_id(params[:id])
    end

    def set_victim
        @victim = Victim.find_by(id: @incident.victim_id)
    end


end

app/controllers/victims/incidents_controller.rb
class Victims::IncidentsController < ApplicationController
    include VictimsHelper

    before_action :require_victim_login
    before_action :verify_user
    before_action :set_incident, only: [:show, :edit, :update, :destroy]

    def index
        @incidents = @victim.incidents
    end

    def new
        if params[:victim_id] && @victim = Victim.find_by(id: params[:victim_id])
            @incident = @victim.incidents.build
        else
            @incident = Incident.new
        end
    end

    def create
        @incident = @victim.incidents.build(incident_params)
        if @incident.save
            redirect_to victim_path(@incident.victim)
        else
            render :new
        end
    end


    def update
        @incident.update(incident_params)
        redirect_to victim_path(@victim)
    end

    def destroy
        @incident.destroy
        redirect_to victim_path(@victim)
    end

    private

    def incident_params
        params.require(:incident).permit(:description, :location, :time_occurred, :request_translator, :contact_status, :language, :volunteer_id, :victim_id)
    end

    def verify_user
        if current_user != Victim.find_by(id: params[:victim_id])
            flash[:error] = "Something went wrong"
            redirect_to victim_path(current_user.id)
        else
            @victim = Victim.find_by(id: params[:victim_id])
        end
    end

    def set_incident
        @incident = @victim.incidents.find(params[:id])
    end

end

app/controllers/victims/users_controller.rb
class Victims::UsersController < ApplicationController
    include VictimsHelper

    before_action :require_victim_login, except: [:login, :new, :create]    
    before_action :set_victim, only: [:show, :edit, :update, :destroy]

    def new
        @victim = Victim.new
    end

    def create
        @victim = Victim.new(user_params)
        if @victim.save
            session[:user_id] = @victim.id
            session[:user_type] = :victim
            redirect_to victim_path(@victim)
        else
            render :new
        end
    end

    def index
        redirect_to victim_path(current_user.id) 
    end


    def update
        @victim.update(user_params)
        redirect_to victim_path(@victim)
    end

    def destroy
        @victim.destroy
        redirect_to root_path
    end

    private

    def user_params
        params.require(:victim).permit(:name, :email, :language, :preferred_contact_method, :contact_info, :password, :password_confirmation)
    end

    def set_victim
        if current_user != Victim.find_by(id: params[:id])
            flash[:error] = "Oops! Something went wrong"
            redirect_to login_path
        else
            @victim = Victim.find_by(id: params[:id])
        end
    end

end

app/controllers/volunteers/incidents_controller.rb
class Volunteers::IncidentsController < ApplicationController
    include VolunteersHelper

    before_action :verify_user
    before_action :require_volunteer_login
    before_action :set_incident, only: [:show, :edit, :update]
    before_action :set_victim, only: [:show, :edit, :update]

    def index
        @incidents = Incident.all
    end

    def edit
        @incident = Incident.find_by(id: params[:incident_id])
    end

    def update
        @incident.update(incident_params)
        redirect_to volunteer_path(@volunteer)
    end

    private

    def incident_params
        params.require(:incident).permit(:description, :location, :time_occurred, :request_translator, :contact_status, :language, :volunteer_id, :victim_id, :notes)
    end

    def verify_user
        if current_user != Volunteer.find_by(id: params[:volunteer_id])
            flash[:error] = "Something went wrong"
            redirect_to volunteer_path(current_user.id)
        else
            @volunteer = Volunteer.find_by(id: params[:volunteer_id])
        end
    end

    def set_incident
        @incident = Incident.find_by(id: params[:id])
    end

    def set_victim
        @victim = Victim.find_by(id: @incident[:victim_id])
    end

end

app/helpers/incidents_helper.rb
module IncidentsHelper

    def require_volunteer_login
        if !logged_in?
          flash[:error] = "You must be logged in to access this section"
          redirect_to login_path
        elsif !is_volunteer?
          flash[:error] = "You must be registered as a volunteer to access this section"
          redirect_to victim_path(current_user.id)
        end
    end

end

app/helpers/victims_helper.rb
module VictimsHelper

    def require_victim_login
        if !logged_in?
            flash[:error] = "Login required for access"
            redirect_to login_path
        elsif !is_victim?
            flash[:error] = "You must be registered as a victim to access"
            redirect_to login_path
        end
    end

end

app/views/victims/incidents/edit.html.erb
<h1> Victim: Edit Reported Incident </h1>

<%= form_with model: [@victim, @incident] do |form| %>
  <input type="hidden" name="incident[victim_id]" value="<%= @victim.id %>">

    <%= form.label :location %>
    <%= form.text_field :location %>
    <br>
    <%= form.label :time_occurred %>
    <%= form.datetime_local_field :time_occurred %>
    <br>
    <%= form.label :request_translator %>
    <%= form.select :request_translator, [["YES"], ["NO"]] %>
    <br>
    <%= form.label :contact_status %>
    <%= form.select :contact_status, [["Not Yet Contacted"], ["Contacted Pending"], ["Contacted"], ["Contact Completed"]] %>
    <br>
    <%= form.label :language %>
    <%= form.text_field :language %>
    <br>
    <%= form.label :description %>
    <%= form.text_area :description %>
    <br>
    <br>
    <%= form.submit %>

<% end %>

<br>
<%= link_to "Back to your profile", victim_path(@victim) %><br>
<%= link_to "Delete Your Incident", [@victim, @incident], method: "delete", data: { confirm: "Are you sure you want to delete your reported incident?" } %>

app/views/victims/incidents/index.html.erb
<h2>Index: Your Reported Incidents</h2>
    <ul>
    <% if @victim.incidents.present? %>
        <% @victim.incidents.each do |incident| %>
          <li>
            Incident Number: <%= incident.id %> <br>
            Location: <%= incident.location %><br>
            Occurred: <%= incident.time_occurred %><br>
            Request Translator: <%= incident.request_translator %><br>
            Volunteer Contact Status: <%= incident.contact_status %><br>
            Preferred Langauge: <%= incident.language %><br>
            Description:  <%= incident.description %><br>

            <%= link_to "View Incident", [@victim, incident] %><br>

          </li>
        <% end %>
      <% else %>
        <li>No Reports Created</li>
            <%= link_to "Create a new Incident", new_victim_incident_path(@victim) %>
      <% end %> 
    </ul>

app/views/victims/incidents/new.html.erb
<h1> Report New Incident </h1>

<% if @incident.errors.any? %>
    <ul>
        <% @incident.errors.full_messages.each do |m| %>
            <li class="error"><%= m %></li>
        <% end %>
    </ul>
<% end %>

<%= form_with model: [@victim, @incident], url: victim_incidents_path do |form| %>
    <%= form.label :location %>
    <%= form.text_field :location %>
    <br>
    <%= form.label :time_occurred %>
    <%= form.datetime_local_field :time_occurred %>
    <br>
    <%= form.label :request_translator %>
    <%= form.select :request_translator, [["YES"], ["NO"]] %>
    <br>
    <%= form.label :contact_status %>
    <%= form.select :contact_status, [["Not Yet Contacted"], ["Contacted Pending"], ["Contacted"], ["Contact Completed"]] %>
    <br>
    <%= form.label :language %>
    <%= form.text_field :language %>
    <br>
    <%= form.label :description %>
    <%= form.text_area :description %>
    <br>
    <br>
    <%= form.submit %>

<% end %>

app/views/victims/incidents/show.html.erb
<h2>Your Reported Incident</h2>
    <ul>
    <% if @incident.present? %>
            Incident Number: <%= @incident.id %> <br>
            Location: <%= @incident.location %><br>
            Occurred: <%= @incident.time_occurred %><br>
            Request Translator: <%= @incident.request_translator %><br>
            Volunteer Contact Status: <%= @incident.contact_status %><br>
            Preferred Langauge: <%= @incident.language %><br>
            Description:  <%= @incident.description %><br>
      <% else %>
        <li>Report Not Created</li>
      <% end %> 
    </ul>
	
<%= link_to "Edit Incident Details", edit_victim_incident_path%>