config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/auth/google_oauth2/callback', to: 'sessions/sessions#omniauth'

  get '/login', to: 'sessions/sessions#login', as: 'login'
  post '/login', to: 'sessions/sessions#create'
  get '/logout', to: 'sessions/sessions#logout', as: 'logout'

  resources :victims, controller: 'victims/users' do
    resources :incidents, controller: 'victims/incidents'
  end

  resources :volunteers, controller: 'volunteers/users' do
    resources :victims, controller: 'volunteers/victims'
    resources :incidents, controller: 'volunteers/incidents'
  end

  resources :incidents, controller: 'incidents/incidents', only: [:index, :show, :update] do
    collection do
      get :not_yet_contacted
      get :not_yet_assigned
      get :time_occurred_desc
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/victim.rb
class Victim < ApplicationRecord
    has_secure_password

    has_many :incidents
    has_many :volunteers, through: :incidents
    accepts_nested_attributes_for :incidents

    validates :name, :email, presence: true
    validates :password, presence: true, on: :create
    validates :email, uniqueness: { case_sensitive: false}
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
    validates :password, confirmation: true, on: :create

end

app/controllers/victims/incidents_controller.rb
class Victims::IncidentsController < ApplicationController
    include VictimsHelper

    before_action :require_victim_login
    before_action :verify_user
    before_action :set_incident, only: [:show, :edit, :update, :destroy]

    def index
        @incidents = @victim.incidents
    end

    def new
        if params[:victim_id] && @victim = Victim.find_by(id: params[:victim_id])
            @incident = @victim.incidents.build
        else
            @incident = Incident.new
        end
    end

    def create
        @incident = @victim.incidents.build(incident_params)
        if @incident.save
            redirect_to victim_path(@incident.victim)
        else
            render :new
        end
    end


    def update
        @incident.update(incident_params)
        redirect_to victim_path(@victim)
    end

    def destroy
        @incident.destroy
        redirect_to victim_path(@victim)
    end

    private

    def incident_params
        params.require(:incident).permit(:description, :location, :time_occurred, :request_translator, :contact_status, :language, :volunteer_id, :victim_id)
    end

    def verify_user
        if current_user != Victim.find_by(id: params[:victim_id])
            flash[:error] = "Something went wrong"
            redirect_to victim_path(current_user.id)
        else
            @victim = Victim.find_by(id: params[:victim_id])
        end
    end

    def set_incident
        @incident = @victim.incidents.find(params[:id])
    end

end

app/controllers/victims/users_controller.rb
class Victims::UsersController < ApplicationController
    include VictimsHelper

    before_action :require_victim_login, except: [:login, :new, :create]    
    before_action :set_victim, only: [:show, :edit, :update, :destroy]

    def new
        @victim = Victim.new
    end

    def create
        @victim = Victim.new(user_params)
        if @victim.save
            session[:user_id] = @victim.id
            session[:user_type] = :victim
            redirect_to victim_path(@victim)
        else
            render :new
        end
    end

    def index
        redirect_to victim_path(current_user.id) 
    end


    def update
        @victim.update(user_params)
        redirect_to victim_path(@victim)
    end

    def destroy
        @victim.destroy
        redirect_to root_path
    end

    private

    def user_params
        params.require(:victim).permit(:name, :email, :language, :preferred_contact_method, :contact_info, :password, :password_confirmation)
    end

    def set_victim
        if current_user != Victim.find_by(id: params[:id])
            flash[:error] = "Oops! Something went wrong"
            redirect_to login_path
        else
            @victim = Victim.find_by(id: params[:id])
        end
    end

end

app/controllers/volunteers/users_controller.rb
class Volunteers::UsersController < ApplicationController
    include VolunteersHelper
    
    before_action :require_volunteer_login, except: [:login, :new, :create]
    before_action :set_volunteer, only: [:show, :edit, :update, :destroy]

    def new
        @volunteer = Volunteer.new
    end

    def create
        @volunteer = Volunteer.new(user_params)
        if @volunteer.save
            session[:user_id] = @volunteer.id
            session[:user_type] = :volunteer
            redirect_to volunteer_path(@volunteer)
        else
            render :new
        end
    end

    def index
        redirect_to volunteer_path(current_user.id) 
    end

    def show
        @volunteered_count = @volunteer.volunteered_count
    end

    def update
        @volunteer.update(user_params)
        redirect_to volunteer_path(@volunteer)
    end

    def destroy
        @volunteer.destroy
        redirect_to root_path
    end

    private

    def user_params
        params.require(:volunteer).permit(:name, :email, :language, :password, :password_confirmation)
    end

    def set_volunteer
        if current_user != Volunteer.find_by(id: params[:id])
            flash[:error] = "Oops! Something went wrong"
            redirect_to login_path        
        else 
            @volunteer = Volunteer.find_by(id: params[:id])
        end
    end

end

app/helpers/victims_helper.rb
module VictimsHelper

    def require_victim_login
        if !logged_in?
            flash[:error] = "Login required for access"
            redirect_to login_path
        elsif !is_victim?
            flash[:error] = "You must be registered as a victim to access"
            redirect_to login_path
        end
    end

end

app/views/victims/users/edit.html.erb
<h1>Edit Victim Profile</h1>

<%= form_with model: @victim do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <br>
    <%= form.label :email %>
    <%= form.text_field :email %>
    <br>
    <%= form.label :language %>
    <%= form.text_field :language %>
    <br>
    <%= form.label :preferred_contact_method %>
    <%= form.text_field :preferred_contact_method %>
    <br>
    <%= form.label :contact_info %>
    <%= form.text_field :contact_info %>
    <br>
    <br>
    <%= form.submit "Update Profile" %>

<% end %>
<br>
<%= link_to "Return to Profile", victim_path(@victim) %>

app/views/victims/users/new.html.erb
<h1>New Victim</h1>
<% if @victim.errors.any? %>
    <ul>
        <% @victim.errors.full_messages.each do |m| %>
            <li class="error"><%= m %></li>
        <% end %>
    </ul>
<% end %>

<%= form_with model: @victim do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <br>
    <%= form.label :email %>
    <%= form.text_field :email %>
    <br>
    <%= form.label :password %>
    <%= form.text_field :password %>
    <br>
    <br>
    <%= form.submit %>

<% end %>

app/views/victims/users/show.html.erb
<h1>Hello <%= @victim.name %></h1>

<h2>Welcome to your profile page.</h2>

<span><strong>Your Email:</strong> <%= @victim.email %></span><br>
<span><strong>Your Language:</strong> <%= @victim.language %></span><br>
<span><strong>Your Preferred Contact Method:</strong> <%= @victim.preferred_contact_method %></span><br>
<span><strong>Your Preferred Contact Details:</strong> <%= @victim.contact_info %></span>
<br>
<br>
<%= link_to "Edit your profile", edit_victim_path(@victim) %><br>

<h2>Your Reported Incidents</h2>
    <ul>
    <% if @victim.incidents.present? %>
        <% @victim.incidents.each do |incident| %>
          <li>
            Location: <%= incident.location %><br>
            Occurred: <%= incident.time_occurred %><br>
            Request Translator: <%= incident.request_translator %><br>
            Volunteer Contact Status: <%= incident.contact_status %><br>
            Preferred Langauge: <%= incident.language %><br>
            Description:  <%= incident.description %><br>

            <%# <%= link_to "View Incident", incident_path(incident) %>
            <%= link_to "View Incident", [@victim, incident] %><br>

          </li>
        <% end %>
      <% else %>
        <li>No Reports Created</li>
        <br>
      <% end %> 
    </ul>

<p><%= link_to "Create a new Incident", new_victim_incident_path(@victim) %></p>
<p><%= link_to "Delete Your Profile", victim_path, method: "delete", data: { confirm: "Are you sure you want to delete your profile?" } %></p>