config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/auth/google_oauth2/callback', to: 'sessions/sessions#omniauth'

  get '/login', to: 'sessions/sessions#login', as: 'login'
  post '/login', to: 'sessions/sessions#create'
  get '/logout', to: 'sessions/sessions#logout', as: 'logout'

  resources :victims, controller: 'victims/users' do
    resources :incidents, controller: 'victims/incidents'
  end

  resources :volunteers, controller: 'volunteers/users' do
    resources :victims, controller: 'volunteers/victims'
    resources :incidents, controller: 'volunteers/incidents'
  end

  resources :incidents, controller: 'incidents/incidents', only: [:index, :show, :update] do
    collection do
      get :not_yet_contacted
      get :not_yet_assigned
      get :time_occurred_desc
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReportHate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <nav>
          <% if logged_in? %>
            <% if is_volunteer? %>
              <%= link_to "Home", volunteer_path(@current_user) %> |
              <%= link_to "Incidents", incidents_path %> |
              <% end %>
            <% if is_victim? %>
              <%= link_to "Home", victim_path(@current_user) %> |
              <%= link_to "New Incident", new_victim_incident_path(@victim) %> |
            <% end %>
            <a href="/logout">Log Out</a>
          <% end %>
        </nav>

        <div id="content">
          <% flash.each do |name, message| %>
            <div class=<%= name %>>
              <%= message %>
            </div>
          <% end %>

        <%= yield %>

        <div class="footer">
        <br>
        <p>Report Hate @2021</p>
        </div>
  </body>
</html>